NUMBER_WORKERS = 2
VAGRANT_BOX    = "generic/ubuntu2204"
Vagrant.configure("2") do |config|
  # config.vm.box = "generic/ubuntu1804"
  # config.vm.box_version = "20191107.0.0"
  config.vm.box_download_insecure = true
  config.vm.define :master do |worker|
    worker.vm.box = VAGRANT_BOX
    worker.vm.hostname = "master"
    worker.vm.network "private_network", ip: "100.0.0.1"
    worker.vm.provider "vmware_desktop" do |v|
      v.ssh_info_public = true
      v.gui = true
      v.linked_clone = false
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
    end
    worker.vm.provision "shell", path: "./scripts/install.sh"
    worker.vm.provision "shell", path: "./scripts/master.sh"
  end
  (1..NUMBER_WORKERS).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = VAGRANT_BOX
      worker.vm.hostname = "worker#{i}"
      worker.vm.network "private_network", ip: "100.0.0.#{i+1}"
      worker.vm.provider "vmware_desktop" do |v|
        v.ssh_info_public = true
        v.gui = true
        v.linked_clone = false
        v.vmx["memsize"] = "2048"
        v.vmx["numvcpus"] = "2"
      end
      worker.vm.provision "shell", path: "./scripts/install.sh"
      worker.vm.provision "shell", path: "./scripts/node.sh", :args => "#{i}"
    end
  end
end